### ISSUE TITLE
MSSQL Module Command Execution does not work

### ISSUE THREAD

**Issue by lenhart** [Pennyw0rth/NetExec#370] opened 2024-07-16 21:25 UTC
**Describe the bug**
On a recent engagement command execution did not work via the MSSQL module. The same command with crackmapexec (version 5.4.0) however worked. 

Differences were that nxc missed the server name in the 3rd column (had 'None' instead), the domain and had the ip as name after the build version in column 4..
After the successful login with the pwned message, there was an additional line with a failed login. cme had the cmd execution output. 

**To Reproduce**
Unfortunately I no longer have access to the system, but this was the output (with dummy data):
Command: `netexec mssql 10.10.10.10 -u username -p password` --local-auth -x whoami
Resulted in:
```
netexec mssql 10.10.10.10 -u username -p password --local-auth -x "whoami"
MSSQL         10.10.10.10  1433    None             [*] Windows 10.0 Build 17763 x64 (name:10.10.10.10) (domain:)
MSSQL         10.10.10.10  1433    None             [+] domain\username:password (Pwned)
MSSQL         10.10.10.10  1433    None             [-] domain\username:password
```

while  the same command w/ crackmapexec resulted in
```
netexec mssql 10.10.10.10 -u username -p password --local-auth -x "whoami"
MSSQL         10.10.10.10  1433    MSSQL-SRV             [*] Windows 10.0 Build 17763 x64 (name:MSSQL-SRV) (domain:MSSQL-SRV)
MSSQL         10.10.10.10  1433    MSSQL-SRV             [+] domain\username:password (Pwned)
MSSQL         10.10.10.10  1433    MSSQL-SRV             [+] Executed command via mssqlexec
MSSQL         10.10.10.10  1433    MSSQL-SRV             ---------------------------
MSSQL         10.10.10.10  1433    MSSQL-SRV            nt-authority/system
```

**Expected behavior**
cme and nxc should behave in the same way.

**Screenshots**
![image](https://github.com/user-attachments/assets/dfb3a601-cde6-456d-80ae-aaea9632ccc6)

**NetExec info**
 - OS: Kali
 - Version of nxc: 1.2
 - Installed from: pipx install (beginning of Juli)

**Comment by NeffIsBack** [comment] 2024-07-16 22:39
Thanks for the bug report! We will take a look at it.

**Comment by Mercury0** [comment] 2024-07-18 23:23
Unable to reproduce. Used HTB Querier as a test case.

![image](https://github.com/user-attachments/assets/c7770780-3840-4fcd-be10-4e6d8262c179)

**Comment by NeffIsBack** [comment] 2024-07-19 00:06
Looks like he used `--local-auth`. That flag does some internal variable changes, my guess is that this fcked things up

**Comment by smcgu** [comment] 2024-07-26 03:22
There is just something generally broken, I think, with MSSQL protocol handling of privileges. The `mssql_priv` module is full of false positives for domain accounts in my current environment. Crackmapexec and manual checks with mssqlclient properly do not flag the account as having sysadmin.

**Comment by NeffIsBack** [comment] 2024-07-26 21:54
So taking a deeper look into this, this is likely an issue with the ntlm challenge. All three "corrupted" information should be retrieved out of the challenge. What is interesting is, that the ntlm challenge did not throw an error, but also didn't provide the needed information. What happens to the rest of the execution is therefore quite ambiguous, hard to say without having a machine for further debugging. If you come across another error like this please let us know!
![image](https://github.com/user-attachments/assets/7efc57c9-03e0-4cf2-a0a7-bcfa044de95d)

**Comment by NeffIsBack** [comment] 2024-08-23 15:55
I will close this for now until we can get more information

**Closed by NeffIsBack** 2024-08-23 15:55 UTC
Labels: bug
