### ISSUE TITLE
RDP not working as expected

### ISSUE THREAD

**Issue by humidnhefty** [Pennyw0rth/NetExec#73] opened 2023-10-13 06:01 UTC
The RDP Password spray works but produces a lot of junk in between for some reason. This doesn't happen for smb or winrm

![image](https://github.com/Pennyw0rth/NetExec/assets/121480971/f0b167d8-8394-4885-919b-29a081b226d0)

Any assistance would be highly appreciated!

**Comment by humidnhefty** [comment] 2023-10-13 14:12
> This is the bug with python 3.12 with async

Any fix you came across?

**Comment by XiaoliChan** [comment] 2023-10-13 14:26
> Any fix you came across?

Not, maybe something needs to change in aardwolf

Reference:
- https://github.com/python/cpython/issues/109490

**Comment by mpgn** [comment] 2023-10-17 14:57
He is using 3.11, strange but cannot reproduce on my side

**Comment by XiaoliChan** [comment] 2023-10-18 07:57
Wired, I downgrade to python 3.11.5 and I still get same issues

![image](https://github.com/Pennyw0rth/NetExec/assets/30458572/0b1c89a5-4082-41f1-a4ae-a8e208e81b03)

**Comment by mpgn** [comment] 2023-10-18 08:24
Sad, but for me it's not related to nxc

**Comment by muelli** [comment] 2023-10-21 11:26
I'm also having problems:

```
└─$ poetry run NetExec rdp 192.168.192.7{0,5} -u jeff -p 'P4a55w0rd!'
Exception ignored in: <function StreamWriter.__del__ at 0x7ff8d7d9c2c0>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/streams.py", line 395, in __del__
  File "/usr/lib/python3.11/asyncio/streams.py", line 343, in close
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 860, in close
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function StreamWriter.__del__ at 0x7ff8d7d9c2c0>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/streams.py", line 395, in __del__
  File "/usr/lib/python3.11/asyncio/streams.py", line 343, in close
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 860, in close
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
RuntimeError: Event loop is closed

```

**Comment by Marshall-Hallenbeck** [comment] 2023-10-21 23:39
@humidnhefty @XiaoliChan @muelli Does this happen consistently for you or randomly? Also can you provide output with the `--debug` flag so we can see what's going on in the background? Right now I can't reproduce this,

**Comment by muelli** [comment] 2023-10-22 16:43
This is 100% reproducible:

```
poetry run NetExec --debug  rdp 192.168.191.145  -u 'Administrator'  -p 'admin'               
[18:42:11] DEBUG    Passed args: Namespace(threads=100, timeout=None, netexec.py:99
                    jitter=None, no_progress=False, verbose=False,                 
                    debug=True, version=False, protocol='rdp',                     
                    target=['192.168.191.145'], cred_id=[],                        
                    username=['Administrator'], password=['admin'],                
                    ignore_pw_decoding=False, kerberos=False,                      
                    no_bruteforce=False, continue_on_success=False,                
                    use_kcache=False, log=None, aesKey=None,                       
                    kdcHost=None, gfail_limit=None, ufail_limit=None,              
                    fail_limit=None, module=None, module_options=[],               
                    list_modules=False, show_module_options=False,                 
                    server='https', server_host='0.0.0.0',                         
                    server_port=None, connectback_host=None, hash=[],              
                    port=3389, rdp_timeout=5, nla_screenshot=False,                
                    domain=None, local_auth=False, screenshot=False,               
                    screentime=10, res='1024x768')                                 
           DEBUG    Protocol: rdp                                    netexec.py:155
           DEBUG    Protocol Path:                                   netexec.py:158
                    /home/kali/NetExec/nxc/protocols/rdp.py                        
           DEBUG    Protocol DB Path:                                netexec.py:160
                    /home/kali/NetExec/nxc/protocols/rdp/database.py               
           DEBUG    symmetric using "pyCryptodomex" for "DES"        __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "TDES"       __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "AES"        __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "RC4"        __init__.py:55
           DEBUG    Protocol Object: <class 'protocol.rdp'>          netexec.py:163
           DEBUG    Protocol DB Object: <class 'protocol.database'>  netexec.py:165
           DEBUG    DB Path:                                         netexec.py:168
                    /home/kali/.nxc/workspaces/default/rdp.db                      
           DEBUG    Using selector: EpollSelector             selector_events.py:54
           DEBUG    Creating ThreadPoolExecutor                       netexec.py:56
           DEBUG    Creating thread for <class 'protocol.rdp'>        netexec.py:59
           INFO     Socket info: host=192.168.191.145,             connection.py:95
                    hostname=192.168.191.145, kerberos=False                       
           DEBUG    Kicking off proto_flow                        connection.py:155
           DEBUG    Using selector: EpollSelector             selector_events.py:54
           DEBUG    Using selector: EpollSelector             selector_events.py:54
           DEBUG    Using selector: EpollSelector             selector_events.py:54
           DEBUG    Using selector: EpollSelector             selector_events.py:54
Exception ignored in: <function StreamWriter.__del__ at 0x7fa4c61b0400>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/streams.py", line 396, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 860, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function StreamWriter.__del__ at 0x7fa4c61b0400>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/streams.py", line 396, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 860, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function StreamWriter.__del__ at 0x7fa4c61b0400>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/streams.py", line 396, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 860, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[18:42:12] DEBUG    hashlib using "pure" for "md4"                    hashlib.py:32
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hashlib using "builtin" for "md5"                 hashlib.py:37
           DEBUG    hashlib using "builtin" for "md5"                 hashlib.py:37
           DEBUG    hashlib using "builtin" for "md5"                 hashlib.py:37
           DEBUG    hashlib using "builtin" for "md5"                 hashlib.py:37
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
RDP         192.168.191.145 3389   OSCP             [*] Windows 10 or Windows Server 2016 Build 19041 (name:OSCP) (domain:oscp) (nla:True)
           INFO     RDP         192.168.191.145 3389   OSCP           logger.py:159
                    [*] Windows 10 or Windows Server 2016 Build 19041              
                    (name:OSCP) (domain:oscp) (nla:True)                           
           DEBUG    Using selector: EpollSelector             selector_events.py:54
           DEBUG    hashlib using "pure" for "md4"                    hashlib.py:32
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hashlib using "builtin" for "md5"                 hashlib.py:37
           DEBUG    hashlib using "builtin" for "md5"                 hashlib.py:37
           DEBUG    hashlib using "builtin" for "md5"                 hashlib.py:37
           DEBUG    hashlib using "builtin" for "md5"                 hashlib.py:37
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
           DEBUG    hmac using "builtin" for "md5"                       hmac.py:42
RDP         192.168.191.145 3389   OSCP             [-] oscp\Administrator:admin (STATUS_LOGON_FAILURE)
           INFO     RDP         192.168.191.145 3389   OSCP           logger.py:159
                    [-] oscp\Administrator:admin                                   
                    (STATUS_LOGON_FAILURE)                                         
Exception ignored in: <function StreamWriter.__del__ at 0x7fa4c61b0400>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/streams.py", line 396, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 860, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function StreamWriter.__del__ at 0x7fa4c61b0400>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/streams.py", line 396, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 860, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
                                             
```

**Comment by NeffIsBack** [comment] 2023-10-22 16:46
@muelli can you give us your exact OS and python version this is happening on? For poetry you can get that info by running `poetry env info`

**Comment by muelli** [comment] 2023-10-22 18:15
This is a Kali:
```
$ lsb_release -a                           
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.4
Codename:       kali-rolling
$
```

```
└─$ poetry env info

Virtualenv
Python:         3.11.6
Implementation: CPython
Path:           /home/kali/.cache/pypoetry/virtualenvs/netexec-zhbX2mAx-py3.11
Executable:     /home/kali/.cache/pypoetry/virtualenvs/netexec-zhbX2mAx-py3.11/bin/python                                                                             
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.11.6
Path:       /usr
Executable: /usr/bin/python3.11
                                                                                   
```

**Comment by Marshall-Hallenbeck** [comment] 2023-10-22 21:07
@muelli what version of Windows is the target host?

**Comment by muelli** [comment] 2023-10-23 17:25
None. It doesn't matter.
having an open nc listener is enough to upset the async.io library:

![image](https://github.com/Pennyw0rth/NetExec/assets/322807/8c9cdf03-0d11-4a2d-ab5a-0ce77ceba3b6)

**Comment by Marshall-Hallenbeck** [comment] 2023-11-22 04:12
I'm running 3.11.4 in my poetry env on Kali and this does not happen on any hosts in my lab, or if I just open a netcat listener. 

@muelli what version of pywinrm is installed in your environment?

**Comment by Cyb3rC3lt** [comment] 2023-11-24 15:55
Same issue for me on-site today. It really dislikes use kcache too which I find very handy at times. It does seem to work on some hosts from the list which (maybe conincidentally) are all set to 'nla:True' but not sure if that is relevant.

![image](https://github.com/Pennyw0rth/NetExec/assets/33097451/2b2931da-c8d0-42ef-aa8c-51d628b5ac68)

**Comment by XiaoliChan** [comment] 2023-11-24 16:18
@Cyb3rC3lt RDP still buggy on event loop stuff

**Comment by jamu85** [comment] 2023-11-25 12:49
Same here on arch 
```bash
$ python --version
Python 3.11.6
$ pipx --version
1.2.1
```

**Comment by NeffIsBack** [comment] 2023-11-25 16:28
I can reproduce it. My best guess would be that it is either an error in python itself or an error in aardwolf. Unfortunetly nxc can't be upgraded to python 3.12 because of dependency problems.

If anyone manages to install nxc using py3.12 let me know how you did it.

**Comment by NeffIsBack** [comment] 2023-12-07 21:02
https://github.com/python/cpython/issues/109538#issuecomment-1823306415

This is apperently fixed in the upstream branches of py3.11 and py3.12, so fixed in the next releases

**Comment by NeffIsBack** [comment] 2023-12-07 21:09
#139 introduces a workaround by simply surpressing all messages to stderr when using rdp. Not the cleanest way but solves the spam until a new python version comes out

**Closed** 2024-01-22 20:50 UTC
Labels: bug
