### ISSUE TITLE
Accounts with admin rights missing (Pwn3d) tag

### ISSUE THREAD

**Issue by bongobongoland** [Pennyw0rth/NetExec#20] opened 2023-09-15 03:10 UTC
I see this on a regular basis.
SMB finds an account but fails to tag it as Pwn3d, even though the account has admin rights.
Maybe I'm missing something.

Windows 10.0 Build 17763
The account is a local account, and the host is not part of any domain.

**Comment by Marshall-Hallenbeck** [comment] 2023-09-15 19:24
@bongobongoland Can you provide some output with the --verbose flag so we can see what's going on?

**Comment by shaaati** [comment] 2023-09-17 12:39
If I had to guess I would say this is due to UAC token filtering.
See, e.g., https://posts.specterops.io/pass-the-hash-is-dead-long-live-localaccounttokenfilterpolicy-506c25a7c167: 

> Tl;dr for any non-RID 500 local admin account remotely connecting to a Windows Vista+ machine, whether through WMI, PSEXEC, or other methods, the token returned is “filtered” (i.e. medium integrity) even though the user is a local administrator. Since there isn’t a method to remotely escalate to a high-integrity context, except through RDP (which needs a plaintext password unless ‘Restricted Admin’ mode is enabled) the token remains medium integrity. So when the user attempts to access a privileged resource remotely, e.g. ADMIN$, they receive an “Access is Denied” message despite technically having administrative access. I’ll get to the RID 500 exception in a bit ;)

Since nxc uses access to the administrative SMB shares to determine administrative privileges of a user, there is no way to identify if a user account is an admin (as far as I know) as long as UAC is active (which it is by default).

**Comment by shaaati** [comment] 2023-09-17 13:03
I'm no expert here,  but as far as I know there is no option. I assume if it were possible to identify admin privileges (even though they could not be used apart from RDP) there would be software out there doing it. In the last years I have not come across such software. 

Once you have a domain account with admin privileges you can verify what local users are in the Administrators group. This is what I most often use during assignments. Only works for domain-joined hosts of course.

**Comment by XiaoliChan** [comment] 2023-09-18 14:02
Yes, this is caused by the UAC stuff

**Comment by zblurx** [comment] 2023-09-29 16:53
Closing since no issue

**Closed by zblurx** 2023-09-29 16:53 UTC
Labels: question
