### ISSUE TITLE
Unable to use NetExec

### ISSUE THREAD

**Issue by dr-war** [Pennyw0rth/NetExec#158] opened 2024-01-03 03:46 UTC
I am unable to run NetExec. I haven't used in in 2-3 weeks, and when I tried to use it today, I got the error relating to "netexec urllib3 (1.26.8) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!". I took several steps to resolve the issue, but nothing has worked, although I do not get the error anymore. Can anyone help? I need nxc for my exam next week.

**Comment by Adamkadaban** [comment] 2024-01-03 04:04
How did you install it and how are you running it? 
I can't see any reason for that to happen if you're running it through poetry or pipx (see the wiki: https://www.netexec.wiki/getting-started/installation)

**Comment by dr-war** [comment] 2024-01-03 04:45
I believe I installed it with pipx. I tried to re-install it, but that didn't help

**Comment by Adamkadaban** [comment] 2024-01-03 06:53
Can you post screenshots? OS Information and the version of nxc that you're using? That'll help with figuring out what the issue is @dr-war

**Comment by dr-war** [comment] 2024-01-03 18:50
![nxc](https://github.com/Pennyw0rth/NetExec/assets/68563427/8911fd2c-1488-4904-a280-6744aad07b24)
![nxcssh](https://github.com/Pennyw0rth/NetExec/assets/68563427/d2452ffa-6d8f-402b-a409-ca1cabc46b14)
![nxcv](https://github.com/Pennyw0rth/NetExec/assets/68563427/403da567-e0fe-48f3-8e39-28a65e488c26)
![OSinfo](https://github.com/Pennyw0rth/NetExec/assets/68563427/ca3f8247-958e-4035-9ff2-6de0f68959c8)
![etc-issue](https://github.com/Pennyw0rth/NetExec/assets/68563427/1de43e95-8c43-4ab3-883f-37e3fc8879a0)

It works with ssh. Now I'm trying to get it to work with smb

**Comment by syrull** [comment] 2024-01-03 21:52
I believe the installation isn't doing something right, can you uninstall `pyreadline`

List the current envs:

```
$ pipx list
```

Then if its called `netexec` or `nxc` do the following:

```
pipx runpip netexec uninstall pyreadline
```

**Comment by NeffIsBack** [comment] 2024-01-04 16:17
Closing, as resolved via discord ticket system

**Closed by NeffIsBack** 2024-01-04 16:17 UTC
Labels: question
