### ISSUE TITLE
Windows binary version: issues with --ntds option

### ISSUE THREAD

**Issue by andretorresbr** [Pennyw0rth/NetExec#156] opened 2023-12-26 15:20 UTC
**Describe the bug**
When I use `--ntds` option in the Windows compiled binary version (single .EXE file), the tools crashes with EOFError.

**To Reproduce**

1. Compile Windows single binary, as described in the [documentation](https://www.netexec.wiki/getting-started/installation/manually-building-the-binaries).
2. Run NetExec with --ntds option:

`.\nxc.exe smb 192.168.144.1 -u syslogagent -H '58a478135a93ac3bf058a5ea0e8fdb71' -d gcbsec.local --ntds`

Resulted in:
![001](https://github.com/Pennyw0rth/NetExec/assets/84332391/af083d58-4527-4b6f-9b05-e36fb1615a51)

**Expected behavior**
NTDS.dit extraction

**Comment by NeffIsBack** [comment] 2023-12-27 17:38
Works fine on my side. Any specifics on how to reproduce the problem?
<img width="877" alt="image" src="https://github.com/Pennyw0rth/NetExec/assets/61382599/4afb09dd-d61b-403e-b76e-f9069294b47e">

**Comment by andretorresbr** [comment] 2023-12-28 02:58
The only different thing is that I ran nxc.exe within a remote PSSession (this fact generates a double hop issue, but nxc.exe does not seem to use the kerberos session, not worrying about this matter).
The weird thing is that it presented the error only when running with `--ntds` option. However, if I specified `--ntds --user administrator`, there was no problem:

![image](https://github.com/Pennyw0rth/NetExec/assets/84332391/c1df3950-848d-4e94-9fe8-eebb2ac14ef7)

**Comment by NeffIsBack** [comment] 2024-01-04 00:14
Hmm okay sounds really weird. I will leave it open for others in the future, but it's really an edge case

**Comment by NeffIsBack** [comment] 2024-10-12 14:35
Gonna close this for now, retried and i can't reproduce the issue. Probably related to pyinstaller itself

**Closed by NeffIsBack** 2024-10-12 14:35 UTC
Labels: bug, windows, not reproducible
